// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Models {
    /// <summary>The type of the album.</summary>
    public enum AlbumBase_album_type
    {
        [EnumMember(Value = "album")]
        Album,
        [EnumMember(Value = "single")]
        Single,
        [EnumMember(Value = "compilation")]
        Compilation,
    }
}
