// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Models {
    /// <summary>The reason for the restriction. Albums may be restricted if the content is not available in a given market, to the user&apos;s subscription type, or when the user&apos;s account is set to not play explicit content.Additional reasons may be added in the future.</summary>
    public enum AlbumRestrictionObject_reason
    {
        [EnumMember(Value = "market")]
        Market,
        [EnumMember(Value = "product")]
        Product,
        [EnumMember(Value = "explicit")]
        Explicit,
    }
}
