// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Models {
    /// <summary>The object type.</summary>
    public enum AlbumBase_type
    {
        [EnumMember(Value = "album")]
        Album,
    }
}
