// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Models {
    /// <summary>The object type.</summary>
    public enum ArtistObject_type
    {
        [EnumMember(Value = "artist")]
        Artist,
    }
}
