// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Spotify.Models {
    public class AudioFeaturesObject : IAdditionalDataHolder, IParsable 
    {
        /// <summary>A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic.</summary>
        public float? Acousticness { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A URL to access the full audio analysis of this track. An access token is required to access this data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnalysisUrl { get; set; }
#nullable restore
#else
        public string AnalysisUrl { get; set; }
#endif
        /// <summary>Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.</summary>
        public float? Danceability { get; set; }
        /// <summary>The duration of the track in milliseconds.</summary>
        public int? DurationMs { get; set; }
        /// <summary>Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.</summary>
        public float? Energy { get; set; }
        /// <summary>The Spotify ID for the track.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Predicts whether a track contains no vocals. &quot;Ooh&quot; and &quot;aah&quot; sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly &quot;vocal&quot;. The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is higher as the value approaches 1.0.</summary>
        public float? Instrumentalness { get; set; }
        /// <summary>The key the track is in. Integers map to pitches using standard [Pitch Class notation](https://en.wikipedia.org/wiki/Pitch_class). E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on. If no key was detected, the value is -1.</summary>
        public int? Key { get; set; }
        /// <summary>Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live.</summary>
        public float? Liveness { get; set; }
        /// <summary>The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track and are useful for comparing relative loudness of tracks. Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typically range between -60 and 0 db.</summary>
        public float? Loudness { get; set; }
        /// <summary>Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0.</summary>
        public int? Mode { get; set; }
        /// <summary>Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks.</summary>
        public float? Speechiness { get; set; }
        /// <summary>The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.</summary>
        public float? Tempo { get; set; }
        /// <summary>An estimated time signature. The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure). The time signature ranges from 3 to 7 indicating time signatures of &quot;3/4&quot;, to &quot;7/4&quot;.</summary>
        public int? TimeSignature { get; set; }
        /// <summary>A link to the Web API endpoint providing full details of the track.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrackHref { get; set; }
#nullable restore
#else
        public string TrackHref { get; set; }
#endif
        /// <summary>The object type.</summary>
        public AudioFeaturesObject_type? Type { get; set; }
        /// <summary>The Spotify URI for the track.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).</summary>
        public float? Valence { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="AudioFeaturesObject"/> and sets the default values.
        /// </summary>
        public AudioFeaturesObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="AudioFeaturesObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static AudioFeaturesObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new AudioFeaturesObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"acousticness", n => { Acousticness = n.GetFloatValue(); } },
                {"analysis_url", n => { AnalysisUrl = n.GetStringValue(); } },
                {"danceability", n => { Danceability = n.GetFloatValue(); } },
                {"duration_ms", n => { DurationMs = n.GetIntValue(); } },
                {"energy", n => { Energy = n.GetFloatValue(); } },
                {"id", n => { Id = n.GetStringValue(); } },
                {"instrumentalness", n => { Instrumentalness = n.GetFloatValue(); } },
                {"key", n => { Key = n.GetIntValue(); } },
                {"liveness", n => { Liveness = n.GetFloatValue(); } },
                {"loudness", n => { Loudness = n.GetFloatValue(); } },
                {"mode", n => { Mode = n.GetIntValue(); } },
                {"speechiness", n => { Speechiness = n.GetFloatValue(); } },
                {"tempo", n => { Tempo = n.GetFloatValue(); } },
                {"time_signature", n => { TimeSignature = n.GetIntValue(); } },
                {"track_href", n => { TrackHref = n.GetStringValue(); } },
                {"type", n => { Type = n.GetEnumValue<AudioFeaturesObject_type>(); } },
                {"uri", n => { Uri = n.GetStringValue(); } },
                {"valence", n => { Valence = n.GetFloatValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("acousticness", Acousticness);
            writer.WriteStringValue("analysis_url", AnalysisUrl);
            writer.WriteFloatValue("danceability", Danceability);
            writer.WriteIntValue("duration_ms", DurationMs);
            writer.WriteFloatValue("energy", Energy);
            writer.WriteStringValue("id", Id);
            writer.WriteFloatValue("instrumentalness", Instrumentalness);
            writer.WriteIntValue("key", Key);
            writer.WriteFloatValue("liveness", Liveness);
            writer.WriteFloatValue("loudness", Loudness);
            writer.WriteIntValue("mode", Mode);
            writer.WriteFloatValue("speechiness", Speechiness);
            writer.WriteFloatValue("tempo", Tempo);
            writer.WriteIntValue("time_signature", TimeSignature);
            writer.WriteStringValue("track_href", TrackHref);
            writer.WriteEnumValue<AudioFeaturesObject_type>("type", Type);
            writer.WriteStringValue("uri", Uri);
            writer.WriteFloatValue("valence", Valence);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
