// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Models {
    /// <summary>The object type.</summary>
    public enum AudiobookBase_type
    {
        [EnumMember(Value = "audiobook")]
        Audiobook,
    }
}
