// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Models {
    /// <summary>The object type.</summary>
    public enum EpisodeBase_type
    {
        [EnumMember(Value = "episode")]
        Episode,
    }
}
