// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Models {
    /// <summary>The object type.</summary>
    public enum PlaylistUserObject_type
    {
        [EnumMember(Value = "user")]
        User,
    }
}
