// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Models {
    /// <summary>The object type.</summary>
    public enum ShowBase_type
    {
        [EnumMember(Value = "show")]
        Show,
    }
}
