// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Models {
    /// <summary>The field is present when getting an artist&apos;s albums. Compare to album_type this field represents relationship between the artist and the album.</summary>
    public enum Tracks_album_group
    {
        [EnumMember(Value = "album")]
        Album,
        [EnumMember(Value = "single")]
        Single,
        [EnumMember(Value = "compilation")]
        Compilation,
        [EnumMember(Value = "appears_on")]
        Appears_on,
    }
}
