// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Search {
    public enum GetTypeQueryParameterType
    {
        [EnumMember(Value = "album")]
        Album,
        [EnumMember(Value = "artist")]
        Artist,
        [EnumMember(Value = "playlist")]
        Playlist,
        [EnumMember(Value = "track")]
        Track,
        [EnumMember(Value = "show")]
        Show,
        [EnumMember(Value = "episode")]
        Episode,
        [EnumMember(Value = "audiobook")]
        Audiobook,
    }
}
