// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Spotify.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Spotify.Search {
    public class SearchGetResponse : IAdditionalDataHolder, IParsable 
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The albums property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PagingSimplifiedAlbumObject? Albums { get; set; }
#nullable restore
#else
        public PagingSimplifiedAlbumObject Albums { get; set; }
#endif
        /// <summary>The artists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PagingArtistObject? Artists { get; set; }
#nullable restore
#else
        public PagingArtistObject Artists { get; set; }
#endif
        /// <summary>The audiobooks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PagingSimplifiedAudiobookObject? Audiobooks { get; set; }
#nullable restore
#else
        public PagingSimplifiedAudiobookObject Audiobooks { get; set; }
#endif
        /// <summary>The episodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PagingSimplifiedEpisodeObject? Episodes { get; set; }
#nullable restore
#else
        public PagingSimplifiedEpisodeObject Episodes { get; set; }
#endif
        /// <summary>The playlists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PagingPlaylistObject? Playlists { get; set; }
#nullable restore
#else
        public PagingPlaylistObject Playlists { get; set; }
#endif
        /// <summary>The shows property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PagingSimplifiedShowObject? Shows { get; set; }
#nullable restore
#else
        public PagingSimplifiedShowObject Shows { get; set; }
#endif
        /// <summary>The tracks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PagingTrackObject? Tracks { get; set; }
#nullable restore
#else
        public PagingTrackObject Tracks { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="SearchGetResponse"/> and sets the default values.
        /// </summary>
        public SearchGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="SearchGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static SearchGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new SearchGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"albums", n => { Albums = n.GetObjectValue<PagingSimplifiedAlbumObject>(PagingSimplifiedAlbumObject.CreateFromDiscriminatorValue); } },
                {"artists", n => { Artists = n.GetObjectValue<PagingArtistObject>(PagingArtistObject.CreateFromDiscriminatorValue); } },
                {"audiobooks", n => { Audiobooks = n.GetObjectValue<PagingSimplifiedAudiobookObject>(PagingSimplifiedAudiobookObject.CreateFromDiscriminatorValue); } },
                {"episodes", n => { Episodes = n.GetObjectValue<PagingSimplifiedEpisodeObject>(PagingSimplifiedEpisodeObject.CreateFromDiscriminatorValue); } },
                {"playlists", n => { Playlists = n.GetObjectValue<PagingPlaylistObject>(PagingPlaylistObject.CreateFromDiscriminatorValue); } },
                {"shows", n => { Shows = n.GetObjectValue<PagingSimplifiedShowObject>(PagingSimplifiedShowObject.CreateFromDiscriminatorValue); } },
                {"tracks", n => { Tracks = n.GetObjectValue<PagingTrackObject>(PagingTrackObject.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<PagingSimplifiedAlbumObject>("albums", Albums);
            writer.WriteObjectValue<PagingArtistObject>("artists", Artists);
            writer.WriteObjectValue<PagingSimplifiedAudiobookObject>("audiobooks", Audiobooks);
            writer.WriteObjectValue<PagingSimplifiedEpisodeObject>("episodes", Episodes);
            writer.WriteObjectValue<PagingPlaylistObject>("playlists", Playlists);
            writer.WriteObjectValue<PagingSimplifiedShowObject>("shows", Shows);
            writer.WriteObjectValue<PagingTrackObject>("tracks", Tracks);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
