// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Spotify.Chapters.Item;
using Spotify.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Spotify.Chapters {
    /// <summary>
    /// Builds and executes requests for operations under \chapters
    /// </summary>
    public class ChaptersRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the Spotify.chapters.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="ChaptersItemRequestBuilder"/></returns>
        public ChaptersItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new ChaptersItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="ChaptersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChaptersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/chapters?ids={ids}{&market*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ChaptersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChaptersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/chapters?ids={ids}{&market*}", rawUrl)
        {
        }
        /// <summary>
        /// Get Spotify catalog information for several chapters identified by their Spotify IDs.&lt;br /&gt;**Note: Chapters are only available for the US, UK, Ireland, New Zealand and Australia markets.**
        /// </summary>
        /// <returns>A <see cref="ChaptersGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="Chapters401Error">When receiving a 401 status code</exception>
        /// <exception cref="Chapters403Error">When receiving a 403 status code</exception>
        /// <exception cref="Chapters429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<ChaptersGetResponse?> GetAsChaptersGetResponseAsync(Action<RequestConfiguration<ChaptersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<ChaptersGetResponse> GetAsChaptersGetResponseAsync(Action<RequestConfiguration<ChaptersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                {"401", Chapters401Error.CreateFromDiscriminatorValue},
                {"403", Chapters403Error.CreateFromDiscriminatorValue},
                {"429", Chapters429Error.CreateFromDiscriminatorValue},
            };
            return await RequestAdapter.SendAsync<ChaptersGetResponse>(requestInfo, ChaptersGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Spotify catalog information for several chapters identified by their Spotify IDs.&lt;br /&gt;**Note: Chapters are only available for the US, UK, Ireland, New Zealand and Australia markets.**
        /// </summary>
        /// <returns>A <see cref="ChaptersResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="Chapters401Error">When receiving a 401 status code</exception>
        /// <exception cref="Chapters403Error">When receiving a 403 status code</exception>
        /// <exception cref="Chapters429Error">When receiving a 429 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsChaptersGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<ChaptersResponse?> GetAsync(Action<RequestConfiguration<ChaptersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<ChaptersResponse> GetAsync(Action<RequestConfiguration<ChaptersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                {"401", Chapters401Error.CreateFromDiscriminatorValue},
                {"403", Chapters403Error.CreateFromDiscriminatorValue},
                {"429", Chapters429Error.CreateFromDiscriminatorValue},
            };
            return await RequestAdapter.SendAsync<ChaptersResponse>(requestInfo, ChaptersResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Spotify catalog information for several chapters identified by their Spotify IDs.&lt;br /&gt;**Note: Chapters are only available for the US, UK, Ireland, New Zealand and Australia markets.**
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<ChaptersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<ChaptersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="ChaptersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public ChaptersRequestBuilder WithUrl(string rawUrl)
        {
            return new ChaptersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get Spotify catalog information for several chapters identified by their Spotify IDs.&lt;br /&gt;**Note: Chapters are only available for the US, UK, Ireland, New Zealand and Australia markets.**
        /// </summary>
        public class ChaptersRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ids")]
            public string? Ids { get; set; }
#nullable restore
#else
            [QueryParameter("ids")]
            public string Ids { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("market")]
            public string? Market { get; set; }
#nullable restore
#else
            [QueryParameter("market")]
            public string Market { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ChaptersRequestBuilderGetRequestConfiguration : RequestConfiguration<ChaptersRequestBuilderGetQueryParameters> 
        {
        }
    }
}
