// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Spotify.AudioAnalysis.Item;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Spotify.AudioAnalysis {
    /// <summary>
    /// Builds and executes requests for operations under \audio-analysis
    /// </summary>
    public class AudioAnalysisRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the Spotify.audioAnalysis.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="AudioAnalysisItemRequestBuilder"/></returns>
        public AudioAnalysisItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new AudioAnalysisItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="AudioAnalysisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AudioAnalysisRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/audio-analysis", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="AudioAnalysisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AudioAnalysisRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/audio-analysis", rawUrl)
        {
        }
    }
}
