// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Spotify.Me.Following {
    /// <summary>The ID type: either `artist` or `user`.</summary>
    public enum ItemType
    {
        [EnumMember(Value = "artist")]
        Artist,
        [EnumMember(Value = "user")]
        User,
    }
}
