// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Spotify.Playlists.Item;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Spotify.Playlists {
    /// <summary>
    /// Builds and executes requests for operations under \playlists
    /// </summary>
    public class PlaylistsRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the Spotify.playlists.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="WithPlaylist_ItemRequestBuilder"/></returns>
        public WithPlaylist_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("playlist_id", position);
                return new WithPlaylist_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="PlaylistsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlaylistsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="PlaylistsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlaylistsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists", rawUrl)
        {
        }
    }
}
